server:
  port: 1234
  tomcat:
    connection-timeout: 50000
  servlet:
    context-path: /silence

spring:
  data:
    redis:
      host: 8.138.84.94
      port: 6400
      password: IB68aIJwf
      jedis:
        pool:
          max-idle: 8
          min-idle: 0
          max-active: 8
          time-between-eviction-runs: 30000