server:
  port: 1234

spring:
  data:
    redis:
      host: 8.138.84.94
      port: 6400
      password: IB68aIJwf
      jedis:
        pool:
          max-idle: 8
          min-idle: 0
          max-active: 8
          min-evictable-idle-time: 60000
          time-between-eviction-runs: 30000